import Foundation
func check(_ condition: @autoclosure () -> Bool, _ message: String) { if !condition() { fatalError(message) } }
var timer = TimerState()
timer.handle("toggle", at: 10)
check(timer.elapsed(at: 20) == 10, "Stopwatch elapsed")
timer.handle("mode:pomodoro", at: 20)
check(timer.stopwatchElapsed == 10 && timer.startedAt == nil, "Mode switch pauses and preserves stopwatch")
check(timer.snapshot(at: 20)["seconds"] as? Double == 1500, "Pomodoro starts at 25 minutes")
timer.handle("toggle", at: 30)
check(timer.snapshot(at: 30.5)["seconds"] as? Double == 1500, "Countdown rounds up")
timer.handle("toggle", at: 40)
check(timer.pomodoroElapsed == 10 && timer.elapsed(at: 200) == 10, "Paused countdown stays fixed")
timer.handle("toggle", at: 300)
check(!timer.tick(at: 1789), "No early finish")
check(timer.tick(at: 1790), "Finish at deadline")
check(timer.completed && timer.startedAt == nil && timer.completedFocusCount == 1, "Finish does not auto-start break")
check(!timer.tick(at: 99999) && timer.completedFocusCount == 1, "Completion fires only once after long sleep")
timer.handle("toggle", at: 100000)
check(timer.phase == .shortBreak && timer.duration == 300, "Start short break")
check(timer.tick(at: 100300), "Break completes")
timer.handle("toggle", at: 100301)
check(timer.phase == .focus && timer.duration == 1500, "Return to focus")
timer.handle("mode:stopwatch", at: 100311)
check(timer.stopwatchElapsed == 10 && timer.pomodoroElapsed == 10, "Both modes retain elapsed time")
timer.handle("reset", at: 100400)
check(timer.stopwatchElapsed == 0 && timer.pomodoroElapsed == 10, "Reset affects only active mode")
var cycle = TimerState(); cycle.mode = .pomodoro
var now = 0.0
for index in 1...4 {
    cycle.handle("toggle", at: now)
    now += 1500; check(cycle.tick(at: now), "Focus finishes")
    check(cycle.completedFocusCount == index, "Count focus completions")
    cycle.handle("toggle", at: now)
    check(cycle.phase == (index == 4 ? .longBreak : .shortBreak), "Fourth session earns long break")
    now += cycle.duration; cycle.tick(at: now)
}
var boundary = TimerState(); boundary.mode = .pomodoro
boundary.handle("toggle", at: 0)
check(boundary.handle("toggle", at: 1500) && boundary.completed && boundary.startedAt == nil, "A pause exactly at deadline must not accidentally start the break")
boundary.handle("reset", at: 1600)
check(!boundary.completed && boundary.pomodoroElapsed == 0, "Reset a completed interval")
print("Passed: countdown, pause/resume, mode preservation, reset isolation, exact completion, sleep overrun, four-session cycle, deadline race.")
var countdown = TimerState(); countdown.mode = .timer
check(countdown.snapshot(at: 0)["seconds"] as? Double == 600, "Default timer is ten minutes")
countdown.handle("adjust:5", at: 0)
check(countdown.timerDuration == 900, "Add five minutes")
countdown.handle("adjust:-10", at: 0)
check(countdown.timerDuration == 300, "Subtract ten minutes")
countdown.handle("toggle", at: 10)
countdown.handle("adjust:10", at: 70)
check(countdown.elapsed(at: 70) == 60 && countdown.snapshot(at: 70)["seconds"] as? Double == 840, "Running adjustment preserves elapsed time")
countdown.handle("toggle", at: 100)
check(countdown.snapshot(at: 1000)["seconds"] as? Double == 810, "Paused adjusted timer stays fixed")
countdown.handle("mode:pomodoro", at: 1100)
check(countdown.snapshot(at: 1100)["seconds"] as? Double == 1500, "Timer adjustment does not affect Pomodoro")
countdown.handle("mode:timer", at: 1200)
check(countdown.snapshot(at: 1200)["seconds"] as? Double == 810, "Countdown preserved across mode switch")
countdown.handle("reset", at: 1200)
check(countdown.snapshot(at: 1200)["seconds"] as? Double == 900, "Reset uses selected duration")
countdown.handle("toggle", at: 1200)
check(countdown.tick(at: 2100) && countdown.isComplete, "Countdown completion")
check(!countdown.tick(at: 2200), "Countdown only completes once")
countdown.handle("toggle", at: 2300)
check(countdown.elapsed(at: 2300) == 0 && !countdown.isComplete, "Restart completed countdown")
countdown.handle("adjust:-10", at: 2300)
check(countdown.handle("adjust:-5", at: 2610), "Expired countdown reports completion before adjustment")
check(countdown.timerDuration == 0 && countdown.startedAt == nil, "Clamp at zero")
countdown.handle("toggle", at: 2700)
check(countdown.startedAt == nil, "Cannot start zero timer")
countdown.handle("adjust:5", at: 2700)
check(countdown.snapshot(at: 2700)["seconds"] as? Double == 300, "Can add time from zero")
for _ in 0..<200 { countdown.handle("adjust:10", at: 2700) }
check(countdown.timerDuration == 86400, "Upper bound of twenty-four hours")
print("Passed: timer adjustments, zero and upper limits, mode isolation, reset, completion, restart.")

var minuteKeys = TimerState(); minuteKeys.mode = .timer
minuteKeys.handle("adjust:1", at: 0)
check(minuteKeys.snapshot(at: 0)["seconds"] as? Double == 660, "One-minute shortcut adds sixty seconds")
minuteKeys.handle("toggle", at: 0)
minuteKeys.handle("adjust:-1", at: 30)
check(minuteKeys.snapshot(at: 30)["seconds"] as? Double == 570 && minuteKeys.startedAt != nil, "One-minute subtraction preserves running state and elapsed time")
minuteKeys.handle("toggle", at: 40)
minuteKeys.handle("adjust:1", at: 100)
check(minuteKeys.snapshot(at: 200)["seconds"] as? Double == 620 && minuteKeys.startedAt == nil, "One-minute addition preserves pause")
minuteKeys.handle("mode:pomodoro", at: 200)
minuteKeys.handle("adjust:-1", at: 200)
check(minuteKeys.duration == 1500 && minuteKeys.timerDuration == 660, "Minute shortcuts affect only Timer mode")
print("Passed: one-minute adjustments while running and paused, and mode isolation.")

var custom = TimerState(); custom.mode = .pomodoro
custom.handle("pomodoro-settings:50,10,30", at: 0)
check(custom.duration == 3000 && custom.startedAt == nil, "50/10 starts paused at fifty minutes")
custom.handle("toggle", at: 0)
custom.handle("pomodoro-settings:50,10,30", at: 60)
check(custom.elapsed(at: 60) == 60 && custom.startedAt != nil, "Applying unchanged settings preserves session")
check(custom.tick(at: 3000), "Custom focus duration completes exactly")
custom.handle("toggle", at: 3000)
check(custom.phase == .shortBreak && custom.duration == 600, "Custom short break duration")
custom.handle("pomodoro-settings:40,8,24", at: 3010)
check(custom.phase == .focus && custom.duration == 2400 && custom.startedAt == nil && custom.completedFocusCount == 0, "Changed settings reset to fresh paused focus")
for action in ["pomodoro-settings:0,5,15", "pomodoro-settings:181,5,15", "pomodoro-settings:25,x,15", "pomodoro-settings:25,5,15,x", "pomodoro-settings:25,5", "pomodoro-settings:25.5,5,15"] {
    custom.handle(action, at: 3010)
    check(custom.focusMinutes == 40 && custom.breakMinutes == 8 && custom.longBreakMinutes == 24, "Invalid settings ignored")
}
custom.completedFocusCount = 3
custom.handle("toggle", at: 4000)
custom.tick(at: 6400)
custom.handle("toggle", at: 6400)
check(custom.phase == .longBreak && custom.duration == 1440, "Fourth focus uses custom long break")
custom.handle("mode:timer", at: 6500)
custom.handle("pomodoro-settings:25,5,15", at: 6500)
check(custom.focusMinutes == 40 && custom.timerDuration == 600, "Settings cannot affect another mode")
check(custom.snapshot(at: 6500)["breakMinutes"] as? Int == 8, "Snapshot exposes configured timings")
print("Passed: Pomodoro presets, custom intervals, unchanged apply, reset semantics, validation and long breaks.")

var updating = TimerState()
updating.handle("mode:timer", at: 0)
updating.handle("toggle", at: 100)
let saved = UpdateCheckpoint(state: updating, now: 160, date: Date(timeIntervalSince1970: 1000))
let encoded = try! JSONEncoder().encode(saved)
let decoded = try! JSONDecoder().decode(UpdateCheckpoint.self, from: encoded)
var resumed = decoded.restored(at: 2, date: Date(timeIntervalSince1970: 1010))
check(resumed.elapsed(at: 2) == 70, "Update includes elapsed restart time")
check(resumed.startedAt != nil, "Update resumes running timer")
check(resumed.tick(at: 532), "Restored timer completes at original deadline")
check(!resumed.tick(at: 533), "Restored completion fires once")
updating.pause(at: 160)
let pausedCheckpoint = UpdateCheckpoint(state: updating, now: 500, date: Date(timeIntervalSince1970: 1000))
let pausedRestore = pausedCheckpoint.restored(at: 0, date: Date(timeIntervalSince1970: 2000))
check(pausedRestore.elapsed(at: 0) == 60 && pausedRestore.startedAt == nil, "Paused timer remains paused across update")
print("Update checkpoint tests passed")
